### ISSUE TITLE
ValueError: Operands could not be broadcast together with shapes (32, 16, 44) (32, 16, 22)

### ISSUE THREAD

**Issue by edowson** [JesperDramsch/keras-complex#1]
I'm trying to run the `cifar10` examples with `tensorflow-gpu==1.13.1` and `keras==2.2.4`.

I get the following error when trying to train using the complex model:
```bash
python scripts/run.py train --datadir $FUEL_DATA_PATH/cifar10 --dataset cifar10 --workdir $OUTPUT_DIR --model complex

ValueError: Operands could not be broadcast together with shapes (32, 16, 44) (32, 16, 22)
```

Would you happen to know how to solve this?

The training script works when using the real model.

**Comment by edowson** [comment]
Attached is a patch that I had to apply, to get keras-complex to run with python-3.6.

```diff
diff --git a/complexnn/__init__.py b/complexnn/__init__.py
index 00b0217..b85e96f 100644
--- a/complexnn/__init__.py
+++ b/complexnn/__init__.py
@@ -6,7 +6,7 @@
 #
 # What this module includes by default:
 from . import bn, conv, dense, init, norm, pool
-# from . import fft
+from . import fft
 
 from .bn import ComplexBatchNormalization as ComplexBN
 from .conv import (
@@ -17,7 +17,7 @@ from .conv import (
     WeightNorm_Conv,
 )
 from .dense import ComplexDense
-# from .fft import (fft, ifft, fft2, ifft2, FFT, IFFT, FFT2, IFFT2)
+from .fft import (fft, ifft, fft2, ifft2, FFT, IFFT, FFT2, IFFT2)
 from .init import (
     ComplexIndependentFilters,
     IndependentFilters,
diff --git a/scripts/run.py b/scripts/run.py
index a576d5d..2d40103 100644
--- a/scripts/run.py
+++ b/scripts/run.py
@@ -26,7 +26,7 @@ class MsgFormatter(L.Formatter):
 	
 	def formatTime(self, record, datefmt):
 		t           = record.created
-		timeFrac    = abs(t-long(t))
+		timeFrac    = abs(t-int(t))
 		timeStruct  = time.localtime(record.created)
 		timeString  = ""
 		timeString += time.strftime("%F %T", timeStruct)
@@ -84,7 +84,7 @@ class Train(Subcommand):
 		argp.add_argument("-l", "--loglevel",       default="info",             type=str,
 		    choices=cls.LOGLEVELS.keys(),
 		    help="Logging severity level.")
-		argp.add_argument("-s", "--seed",           default=0xe4223644e98b8e64, type=long,
+		argp.add_argument("-s", "--seed",           default=0xe4223644e98b8e64, type=int,
 		    help="Seed for PRNGs.")
 		argp.add_argument("--summary",     action="store_true",
 		    help="""Print a summary of the network.""")
@@ -196,8 +196,7 @@ def getArgParser(prog):
 	argp = Ap.ArgumentParser(prog        = prog,
 	                         usage       = None,
 	                         description = None,
-	                         epilog      = None,
-	                         version     = __version__)
+	                         epilog      = None)
 	subp = argp.add_subparsers()
 	argp.set_defaults(argp=argp)
 	argp.set_defaults(subp=subp)
@@ -207,7 +206,7 @@ def getArgParser(prog):
 	
 	
 	# Add subcommands
-	for v in globals().itervalues():
+	for v in globals().values():
 		if(isinstance(v, type)       and
 		   issubclass(v, Subcommand) and
 		   v != Subcommand):
diff --git a/scripts/training.py b/scripts/training.py
index 318bf99..99f37aa 100644
--- a/scripts/training.py
+++ b/scripts/training.py
@@ -150,7 +150,7 @@ def getResnetModel(d):
 	activation    = d.act
 	advanced_act  = d.aact
 	drop_prob     = d.dropout
-	inputShape    = (3, 32, 32) if K.image_dim_ordering() == "th" else (32, 32, 3)
+	inputShape    = (3, 32, 32) if K.image_data_format() == "channels_first" else (32, 32, 3)
 	channelAxis   = 1 if K.image_data_format() == 'channels_first' else -1
 	filsize       = (3, 3)
 	convArgs      = {
@@ -196,7 +196,7 @@ def getResnetModel(d):
 	# Stage 2
 	#
 	
-	for i in xrange(n):
+	for i in range(n):
 		O = getResidualBlock(O, filsize, [sf, sf], 2, str(i), 'regular', convArgs, bnArgs, d)
 		if i == n//2 and d.spectral_pool_scheme == "stagemiddle":
 			O = applySpectralPooling(O, d)
@@ -209,7 +209,7 @@ def getResnetModel(d):
 	if d.spectral_pool_scheme == "nodownsample":
 		O = applySpectralPooling(O, d)
 	
-	for i in xrange(n-1):
+	for i in range(n-1):
 		O = getResidualBlock(O, filsize, [sf*2, sf*2], 3, str(i+1), 'regular', convArgs, bnArgs, d)
 		if i == n//2 and d.spectral_pool_scheme == "stagemiddle":
 			O = applySpectralPooling(O, d)
@@ -222,7 +222,7 @@ def getResnetModel(d):
 	if d.spectral_pool_scheme == "nodownsample":
 		O = applySpectralPooling(O, d)
 	
-	for i in xrange(n-1):
+	for i in range(n-1):
 		O = getResidualBlock(O, filsize, [sf*4, sf*4], 4, str(i+1), 'regular', convArgs, bnArgs, d)
 		if i == n//2 and d.spectral_pool_scheme == "stagemiddle":
 			O = applySpectralPooling(O, d)
```

**Comment by JesperDramsch** [comment]
Thank you so much for posting this here. 

To be honest, I completely forgot to adjust these scripts from the original fork. I'm so sorry for the hassle. Would it be ok for you to submit a PR with the patch? 

I'll go through the scripts, in addition, to make sure they're working.

**Comment by edowson** [comment]
I've created a pull request here: 
[Fixes for Python3 and Keras-2.3.1 #2](https://github.com/JesperDramsch/keras-complex/pull/2)

I also updated my keras version to 2.3.1. The following changes should work fine for both keras-2.2.4 and keras-2.3.1:
[scripts/training.py: Use keras.backend.image_data_format() to support newer keras version.](https://github.com/JesperDramsch/keras-complex/pull/2/commits/861f8b7612fbaf0a1a7ae0c527994add44312ca4)

**Comment by edowson** [comment]
If I run the code with `tensorflow-gpu==2.1.0` and `keras==2.3.1`, there error is a bit different:
```bash
Traceback (most recent call last):
  File "scripts/run.py", line 225, in <module>
    main(sys.argv)
  File "scripts/run.py", line 223, in main
    return d.__subcmdfn__(d)
  File "scripts/run.py", line 182, in run
    import training; training.train(d)
  File "/mnt/storage/mount/project/communications/tutorial/rfmls/deep-complex-networks/third-party/jesper-dramsch/keras-complex/scripts/training.py", line 608, in train
    model = getResnetModel(d)
  File "/mnt/storage/mount/project/communications/tutorial/rfmls/deep-complex-networks/third-party/jesper-dramsch/keras-complex/scripts/training.py", line 193, in getResnetModel
    O = ComplexBN(name="bn_conv1_2a", **bnArgs)(O)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "./complexnn/bn.py", line 345, in build
    constraint=self.gamma_diag_constraint)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/keras/engine/base_layer.py", line 282, in add_weight
    constraint=constraint)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 620, in variable
    value, dtype=dtype, name=name, constraint=constraint)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 814, in variable
    constraint=constraint)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2645, in default_variable_creator_v2
    shape=shape)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "/tool/python/conda/env/dcn3.6/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1494, in _init_from_args
    raise ValueError("Tensor-typed variable initializers must either be "
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.
```

**Comment by JesperDramsch** [comment]
I haven't ported this to TF2 yet, so I'd expect this to break.

**Comment by edowson** [comment]
It’s okay if you can get it working with tf-1.13.1.

**Comment by JesperDramsch** [comment]
Awesome

Elvis Dowson <notifications@github.com> schrieb am So., 10. Mai 2020, 19:26:

**Comment by JesperDramsch** [comment]
[Redacted]

Archiving the email here, after I asked to use Github issues to track the progress, the yelling was apparently preferred in private.

**Comment by JesperDramsch** [comment]
Keeping an archive here, because I keep being harassed by this individual.

[Redacted]

**Comment by JesperDramsch** [comment]
This is still an issue, therefore, it has to stay open until it is dealt with.

**Comment by amrrs** [comment]
It's such a shame that people like @edowson take anything for granted
