### ISSUE TITLE
Error in ComplexBatchNormalization

### ISSUE THREAD

**Issue by pelavoie** [JesperDramsch/keras-complex#6]
Hello,

I keep running into this error with ComplexBatchNormalization when training a simple model.

```
Traceback (most recent call last):
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable complex_batch_normalization_2/Variable_3 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/complex_batch_normalization_2/Variable_3)
         [[{{node complex_batch_normalization_2/ReadVariableOp_3}}]]
```

I even reproduced it while running src/mass_train.py in https://github.com/JesperDramsch/Complex-CNN-Seismic

Any idea what could be the cause?

I am using python=3.6, tensorflow-gpu=1.15.2, keras=2.3.1.

**Comment by JesperDramsch** [comment]
Hey @pelavoie,

thanks for the issue, it seems like this may have to do with tensorflow not being threadsafe. Others had this problem on tensorflow itself, it seems. Could you try this solution? 

https://github.com/tensorflow/tensorflow/issues/28287

**Comment by pelavoie** [comment]
Hi @JesperDramsch,

I tried the solution (initialize variables and run training inside a session) but still get the same error. I reproduced with the complexnn example in the README:

```
import complexnn

import keras
from keras import models
from keras import layers
from keras import optimizers

import tensorflow as tf
sess = tf.Session()

model = models.Sequential()

model.add(complexnn.conv.ComplexConv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 2)))
model.add(complexnn.bn.ComplexBatchNormalization())
model.add(layers.MaxPooling2D((2, 2), padding='same'))

model.compile(optimizer=optimizers.Adam(), loss='mse')

init_op = tf.global_variables_initializer()
sess.run(init_op)
```

Here is the complete call stack I get. Seems to involve the `sqrt_init` initializer in `bn.py` ?
I am really stumped now. It's either something really obvious or very obscure.

```
Traceback (most recent call last):
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable complex_batch_normalization_1/Variable_3 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/complex_batch_normalization_1/Variable_3)
         [[{{node complex_batch_normalization_1/ReadVariableOp_3}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/phlav/modrec/reduce.py", line 22, in <module>
    sess.run(init_op)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/data/phlav/complex-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable complex_batch_normalization_1/Variable_3 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/complex_batch_normalization_1/Variable_3)
         [[node complex_batch_normalization_1/ReadVariableOp_3 (defined at /complex-env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'complex_batch_normalization_1/ReadVariableOp_3':
  File "/modrec/reduce.py", line 16, in <module>
    model.add(complexnn.bn.ComplexBatchNormalization())
  File "/complex-env/lib/python3.6/site-packages/keras/engine/sequential.py", line 182, in add
    output_tensor = layer(self.outputs[0])
  File "/complex-env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/complex-env/lib/python3.6/site-packages/complexnn/bn.py", line 363, in build
    trainable=False)
  File "/complex-env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "/complex-env/lib/python3.6/site-packages/complexnn/bn.py", line 21, in sqrt_init
    value = (1 / np.sqrt(2)) * K.ones(shape)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 1079, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 524, in value
    return self._read_variable_op()
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 608, in _read_variable_op
    self._dtype)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 587, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/complex-env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by JesperDramsch** [comment]
Sorry for the misunderstanding, I was referring to this comment in particular that seems to have solved issues for a similar problem. https://github.com/tensorflow/tensorflow/issues/28287#issuecomment-495005162

```
import complexnn

import keras
from keras import models
from keras import layers
from keras import optimizers

from tensorflow.python.keras.backend import set_session

import tensorflow as to

sess = tf.Session()
graph = tf.get_default_graph()

set_session(sess)

model = models.Sequential()

model.add(complexnn.conv.ComplexConv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 2)))
model.add(complexnn.bn.ComplexBatchNormalization())
model.add(layers.MaxPooling2D((2, 2), padding='same'))

model.compile(optimizer=optimizers.Adam(), loss='mse')
```

My problem is that I've never run into this issue on two entirely different platforms. Have you tried it with the pinned versions `tensorflow-gpu==1.13.1` and `keras==2.2.4` and reproduced the error?

**Comment by pelavoie** [comment]
Yes, using the pinned versions fixes the issue. I cannot reproduce the error.

Somehow I had assumed that the latest pull request https://github.com/JesperDramsch/keras-complex/pull/2 also added support for tensorflow==1.15.2.

Thanks!
